/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.36
 * Generated at: 2020-03-28 16:07:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.templates.site;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class footer_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<!--footer section start-->\r\n");
      out.write("\t\t\t\t\t<footer>\r\n");
      out.write("\t\t\t\t\t\t<p>Create by <a href=\"https://github.com/Feliphegomez\" target=\"_blank\">FelipheGomez.</a></p>\r\n");
      out.write("\t\t\t\t\t</footer>\r\n");
      out.write("\t\t\t\t\t<!--footer section end-->\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!--//content-inner-->\r\n");
      out.write("\t\t\t<!--/sidebar-menu-->\r\n");
      out.write("\t\t\t<div class=\"sidebar-menu\">\r\n");
      out.write("\t\t\t\t<header class=\"logo\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" class=\"sidebar-icon\"> <span class=\"fa fa-bars\"></span> </a> <a href=\"index.jsp\"> <span id=\"logo\"> <h1>Augment</h1></span> \r\n");
      out.write("\t\t\t\t\t\t<!--<img id=\"logo\" src=\"\" alt=\"Logo\"/>--> \r\n");
      out.write("\t\t\t  \t\t</a> \r\n");
      out.write("\t\t\t\t</header>\r\n");
      out.write("\t\t\t\t<div style=\"border-top:1px solid rgba(69, 74, 84, 0.7)\"></div>\r\n");
      out.write("\t\t\t\t\t<!--/down-->\r\n");
      out.write("\t\t\t\t\t<div class=\"down\">\t\r\n");
      out.write("\t\t\t\t\t  \t<!-- <a href=\"index.jsp\"><img src=\"images/admin.jpg\"></a>-->\r\n");
      out.write("\t\t\t\t\t  \t<a href=\"index.jsp\"><span class=\" name-caret\">");
      out.print( (String)session.getAttribute("firstname") );
      out.write(' ');
      out.print( (String)session.getAttribute("lastname") );
      out.write("</span></a>\r\n");
      out.write("\t\t\t\t\t\t <p>\r\n");
      out.write("\t\t\t\t\t\t\t ");
 Integer userid = (Integer)session.getAttribute("userid"); 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t ");
      out.print( userid );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t ");
      out.print( (String)session.getAttribute("username") );
      out.write("\r\n");
      out.write("\t\t\t\t\t \t</p>\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<!-- <li><a class=\"tooltips\" href=\"index.jsp\"><span>Profile</span><i class=\"lnr lnr-user\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a class=\"tooltips\" href=\"index.jsp\"><span>Settings</span><i class=\"lnr lnr-cog\"></i></a></li> -->\r\n");
      out.write("\t\t\t\t\t\t\t<li><a class=\"tooltips\" href=\"Logout\"><span>Salir </span><i class=\"lnr lnr-power-switch\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t    <!--//down-->\r\n");
      out.write("                \t<div class=\"menu\">\r\n");
      out.write("\t\t\t\t\t\t<ul id=\"menu\" >\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"index.jsp\"><i class=\"fa fa-tachometer\"></i> <span>Dashboard</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li id=\"menu-academico\" ><a href=\"#\"><i class=\"fa fa-table\"></i> <span> Tabs &amp; Panels</span> <span class=\"fa fa-angle-right\" style=\"float: right\"></span></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul id=\"menu-academico-sub\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li id=\"menu-academico-avaliacoes\" ><a href=\"tabs.html\"> Tabs &amp; Panels</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li id=\"menu-academico-boletim\" ><a href=\"widget.html\">Widgets</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li id=\"menu-academico-avaliacoes\" ><a href=\"calender.html\">Calendar</a></li>\t\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li id=\"menu-academico\" ><a href=\"#\"><i class=\"fa fa-file-text-o\"></i> <span>Ui Elements</span> <span class=\"fa fa-angle-right\" style=\"float: right\"></span></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul id=\"menu-academico-sub\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li id=\"menu-academico-avaliacoes\" ><a href=\"forms.html\">Forms</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li id=\"menu-academico-boletim\" ><a href=\"validation.html\">Validation Forms</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li id=\"menu-academico-boletim\" ><a href=\"table.html\">Tables</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li id=\"menu-academico-boletim\" ><a href=\"buttons.html\">Buttons</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"typography.html\"><i class=\"lnr lnr-pencil\"></i> <span>Typography</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li id=\"menu-academico\" ><a href=\"#\"><i class=\"lnr lnr-book\"></i> <span>Pages</span> <span class=\"fa fa-angle-right\" style=\"float: right\"></span></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul id=\"menu-academico-sub\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t    <li id=\"menu-academico-avaliacoes\" ><a href=\"login.html\">Login</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t    <li id=\"menu-academico-boletim\" ><a href=\"register.html\">Register</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li id=\"menu-academico-boletim\" ><a href=\"404.html\">404</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li id=\"menu-academico-boletim\" ><a href=\"sign.html\">Sign up</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li id=\"menu-academico-boletim\" ><a href=\"profile.html\">Profile</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\"><i class=\"lnr lnr-envelope\"></i> <span>Mail Box</span><span class=\"fa fa-angle-right\" style=\"float: right\"></span></a>\r\n");
      out.write("\t\t\t\t\t\t\t   \t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"inbox.html\"><i class=\"fa fa-inbox\"></i> Inbox</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"compose.html\"><i class=\"fa fa-pencil-square-o\"></i> Compose Mail</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"editor.html\"><span class=\"lnr lnr-highlight\"></span> Editors Page</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t  \t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t        <li id=\"menu-academico\" ><a href=\"#\"><i class=\"lnr lnr-layers\"></i> <span>Components</span> <span class=\"fa fa-angle-right\" style=\"float: right\"></span></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t <ul id=\"menu-academico-sub\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li id=\"menu-academico-avaliacoes\" ><a href=\"grids.html\">Grids</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li id=\"menu-academico-boletim\" ><a href=\"media.html\">Media Objects</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"chart.html\"><i class=\"lnr lnr-chart-bars\"></i> <span>Charts</span> <span class=\"fa fa-angle-right\" style=\"float: right\"></span></a>\r\n");
      out.write("\t\t\t\t\t\t\t  \t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"map.html\"><i class=\"lnr lnr-map\"></i> Maps</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"graph.html\"><i class=\"lnr lnr-apartment\"></i> Graph Visualization</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li id=\"menu-comunicacao\" ><a href=\"#\"><i class=\"fa fa-smile-o\"></i> <span>More</span><span class=\"fa fa-angle-double-right\" style=\"float: right\"></span></a>\r\n");
      out.write("\t\t\t\t\t\t\t  \t<ul id=\"menu-comunicacao-sub\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li id=\"menu-mensagens\" style=\"width:120px\" ><a href=\"project.html\">Projects <i class=\"fa fa-angle-right\" style=\"float: right; margin-right: -8px; margin-top: 2px;\"></i></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<ul id=\"menu-mensagens-sub\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li id=\"menu-mensagens-enviadas\" style=\"width:130px\" ><a href=\"ribbon.html\">Ribbons</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li id=\"menu-mensagens-recebidas\"  style=\"width:130px\"><a href=\"blank.html\">Blank</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li id=\"menu-arquivos\" ><a href=\"500.html\">500</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"clearfix\"></div>\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
