/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.36
 * Generated at: 2020-03-28 16:26:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.templates.site;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class header_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE HTML>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<title>Hulk Store :: Todo1.com</title>\r\n");
      out.write("\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("\t<meta name=\"keywords\" content=\"Augment Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template, \r\n");
      out.write("\tSmartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design\" />\r\n");
      out.write("\t<script type=\"application/x-javascript\"> addEventListener(\"load\", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>\r\n");
      out.write("\t <!-- Bootstrap Core CSS -->\r\n");
      out.write("\t<link href=\"css/bootstrap.min.css\" rel='stylesheet' type='text/css' />\r\n");
      out.write("\t<!-- Custom CSS -->\r\n");
      out.write("\t<link href=\"css/style.css\" rel='stylesheet' type='text/css' />\r\n");
      out.write("\t<!-- Graph CSS -->\r\n");
      out.write("\t<link href=\"css/font-awesome.css\" rel=\"stylesheet\"> \r\n");
      out.write("\t<!-- jQuery -->\r\n");
      out.write("\t<link href='//fonts.googleapis.com/css?family=Roboto:700,500,300,100italic,100,400' rel='stylesheet' type='text/css'>\r\n");
      out.write("\t<!-- lined-icons -->\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"css/icon-font.min.css\" type='text/css' />\r\n");
      out.write("\t<!-- //lined-icons -->\r\n");
      out.write("\t<script src=\"js/jquery-1.10.2.min.js\"></script>\r\n");
      out.write("\t<script src=\"js/amcharts.js\"></script>\t\r\n");
      out.write("\t<script src=\"js/serial.js\"></script>\t\r\n");
      out.write("\t<script src=\"js/light.js\"></script>\t\r\n");
      out.write("\t<script src=\"js/radar.js\"></script>\t\r\n");
      out.write("\t<link href=\"css/barChart.css\" rel='stylesheet' type='text/css' />\r\n");
      out.write("\t<link href=\"css/fabochart.css\" rel='stylesheet' type='text/css' />\r\n");
      out.write("\t<!--clock init-->\r\n");
      out.write("\t<script src=\"js/css3clock.js\"></script>\r\n");
      out.write("\t<!--Easy Pie Chart-->\r\n");
      out.write("\t<!--skycons-icons-->\r\n");
      out.write("\t<script src=\"js/skycons.js\"></script>\r\n");
      out.write("\t\r\n");
      out.write("\t<script src=\"js/jquery.easydropdown.js\"></script>\r\n");
      out.write("    <script src=\"https://unpkg.com/vue/dist/vue.js\"></script>\r\n");
      out.write("\t<script src=\"https://unpkg.com/vue-router/dist/vue-router.js\"></script>\r\n");
      out.write("\t<script src=\"https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!--//skycons-icons-->\r\n");
      out.write("</head> \r\n");
      out.write("<body>\r\n");
      out.write("   <div class=\"page-container\" id=\"vue_app\">\r\n");
      out.write("   <!--/content-inner-->\r\n");
      out.write("\t<div class=\"left-content\">\r\n");
      out.write("\t   <div class=\"inner-content\">\r\n");
      out.write("\t\t<!-- header-starts -->\r\n");
      out.write("\t\t\t<div class=\"header-section\">\r\n");
      out.write("\t\t\t\t\t\t<!--menu-right-->\r\n");
      out.write("\t\t\t\t\t\t<div class=\"top_menu\">\r\n");
      out.write("\t\t\t\t\t\t        <div class=\"main-search\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<form>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t   <input type=\"text\" value=\"Search\" onFocus=\"this.value = '';\" onBlur=\"if (this.value == '') {this.value = 'Search';}\" class=\"text\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"submit\" value=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"close\"><img src=\"images/cross.png\" /></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"srch\"><button></button></div>\r\n");
      out.write("\t\t\t\t\t\t\t<!--/profile_details-->\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"profile_details_left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul class=\"nofitications-dropdown\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li class=\"dropdown note dra-down\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t   <div id=\"dd\" class=\"wrapper-dropdown-3\" tabindex=\"1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<span>Italy</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<ul class=\"dropdown\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<li><a class=\"deutsch\">France</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<li><a class=\"english\"> Italy</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<li><a class=\"espana\">Brazil</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<li><a class=\"russian\">Usa</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t    </li>\r\n");
      out.write("\t\t\t\t\t\t\t\t       <li class=\"dropdown note\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\" aria-expanded=\"false\"><i class=\"fa fa-envelope-o\"></i> <span class=\"badge\">3</span></a>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<ul class=\"dropdown-menu two first\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"notification_header\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<h3>You have 3 new messages  </h3> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t   <div class=\"user_img\"><img src=\"images/1.jpg\" alt=\"\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t   <div class=\"notification_desc\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<p>Lorem ipsum dolor sit amet</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<p><span>1 hour ago</span></p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t   <div class=\"clearfix\"></div>\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t </a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t <li class=\"odd\"><a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"user_img\"><img src=\"images/in.jpg\" alt=\"\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t   <div class=\"notification_desc\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<p>Lorem ipsum dolor sit amet </p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<p><span>1 hour ago</span></p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t  <div class=\"clearfix\"></div>\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t </a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t   <div class=\"user_img\"><img src=\"images/in1.jpg\" alt=\"\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t   <div class=\"notification_desc\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<p>Lorem ipsum dolor sit amet </p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<p><span>1 hour ago</span></p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t   <div class=\"clearfix\"></div>\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"notification_bottom\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"#\">See all messages</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"dropdown note\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\" aria-expanded=\"false\"><i class=\"fa fa-bell-o\"></i> <span class=\"badge\">5</span></a>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul class=\"dropdown-menu two\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"notification_header\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<h3>You have 5 new notification</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"user_img\"><img src=\"images/in.jpg\" alt=\"\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t   <div class=\"notification_desc\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<p>Lorem ipsum dolor sit amet</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<p><span>1 hour ago</span></p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t  <div class=\"clearfix\"></div>\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t </a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t <li class=\"odd\"><a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"user_img\"><img src=\"images/in5.jpg\" alt=\"\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t   <div class=\"notification_desc\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<p>Lorem ipsum dolor sit amet </p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<p><span>1 hour ago</span></p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t   <div class=\"clearfix\"></div>\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t </a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t <li><a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"user_img\"><img src=\"images/in8.jpg\" alt=\"\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t   <div class=\"notification_desc\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<p>Lorem ipsum dolor sit amet </p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<p><span>1 hour ago</span></p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t   <div class=\"clearfix\"></div>\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t </a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t <li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"notification_bottom\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"#\">See all notification</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\t\r\n");
      out.write("\t\t\t\t\t\t<li class=\"dropdown note\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\" aria-expanded=\"false\"><i class=\"fa fa-tasks\"></i> <span class=\"badge blue1\">9</span></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<ul class=\"dropdown-menu two\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"notification_header\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<h3>You have 9 pending task</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"task-info\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"task-desc\">Database update</span><span class=\"percentage\">40%</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"clearfix\"></div>\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t   </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"progress progress-striped active\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t <div class=\"bar yellow\" style=\"width:40%;\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"index.jsp\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"task-info\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"task-desc\">Dashboard done</span><span class=\"percentage\">90%</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t   <div class=\"clearfix\"></div>\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t   \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"progress progress-striped active\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t <div class=\"bar green\" style=\"width:90%;\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"task-info\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"task-desc\">Mobile App</span><span class=\"percentage\">33%</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"clearfix\"></div>\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t   <div class=\"progress progress-striped active\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t <div class=\"bar red\" style=\"width: 33%;\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"task-info\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"task-desc\">Issues fixed</span><span class=\"percentage\">80%</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t   <div class=\"clearfix\"></div>\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"progress progress-striped active\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t <div class=\"bar  blue\" style=\"width: 80%;\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"notification_bottom\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"#\">See all pending task</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\t\t   \t\t\t\t\t\t\t   \t\t\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"clearfix\"></div>\t\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"clearfix\"></div>\t\r\n");
      out.write("\t\t\t\t\t\t\t<!--//profile_details-->\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<!--//menu-right-->\r\n");
      out.write("\t\t\t\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<!-- //header-ends -->\r\n");
      out.write("\t\t\t\t\t<div class=\"outter-wp\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"colm-sm-12\">");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
