/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.36
 * Generated at: 2020-03-26 15:28:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE HTML>\r\n");
      out.write("<html>\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<title>Hulk Store | Login :: Todo1.com</title>\r\n");
      out.write("\t\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\t\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("\t\t<meta name=\"keywords\" content=\"Augment Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template, \r\n");
      out.write("\t\tSmartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design\" />\r\n");
      out.write("\t\t<script type=\"application/x-javascript\"> addEventListener(\"load\", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>\r\n");
      out.write("\t\t <!-- Bootstrap Core CSS -->\r\n");
      out.write("\t\t<link href=\"css/bootstrap.min.css\" rel='stylesheet' type='text/css' />\r\n");
      out.write("\t\t<!-- Custom CSS -->\r\n");
      out.write("\t\t<link href=\"css/style.css\" rel='stylesheet' type='text/css' />\r\n");
      out.write("\t\t<!-- Graph CSS -->\r\n");
      out.write("\t\t<link href=\"css/font-awesome.css\" rel=\"stylesheet\"> \r\n");
      out.write("\t\t<!-- jQuery -->\r\n");
      out.write("\t\t<link href='//fonts.googleapis.com/css?family=Roboto:700,500,300,100italic,100,400' rel='stylesheet' type='text/css'>\r\n");
      out.write("\t\t<!-- lined-icons -->\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"css/icon-font.min.css\" type='text/css' />\r\n");
      out.write("\t\t<!-- //lined-icons -->\r\n");
      out.write("\t\t<script src=\"js/jquery-1.10.2.min.js\"></script>\r\n");
      out.write("\t\t<!--clock init-->\r\n");
      out.write("\t</head> \r\n");
      out.write("\t<body>\r\n");
      out.write("\t\t<!--/login-->\r\n");
      out.write("\t\t<div class=\"error_page\">\r\n");
      out.write("\t\t\t<!--/login-top-->\r\n");
      out.write("\t\t\t<div class=\"error-top\">\r\n");
      out.write("\t\t\t\t<h2 class=\"inner-tittle page\">HulkStore</h2>\r\n");
      out.write("\t\t\t\t    <div class=\"login\">\r\n");
      out.write("\t\t\t\t\t<h3 class=\"inner-tittle t-inner\">Ingresar</h3>\r\n");
      out.write("\t\t\t\t\t\t<!-- // \r\n");
      out.write("\t\t\t\t\t\t<div class=\"buttons login\">\r\n");
      out.write("\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\" class=\"hvr-sweep-to-right\">Facebook</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li class=\"lost\"><a href=\"#\" class=\"hvr-sweep-to-left\">Twitter</a> </li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t-->\r\n");
      out.write("\t\t\t\t\t\t<form action=\"index.jsp\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" name=\"username\" class=\"text\" value=\"Usuario\" onfocus=\"this.value = '';\" onblur=\"if (this.value == '') {this.value = 'Usuario';}\" >\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"password\" value=\"password\" name=\"password\" onfocus=\"this.value = '';\" onblur=\"if (this.value == '') {this.value = 'Password';}\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"submit\"><input type=\"submit\" onclick=\"myFunction()\" value=\"Login\" ></div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"new\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- // <p><label class=\"checkbox11\"><input type=\"checkbox\" name=\"checkbox\"><i> </i>Forgot Password ?</label></p> -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"sign\">Do not have an account ? <a href=\"sign.html\">Sign Up</a></p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t<!--//login-top-->\r\n");
      out.write("\t\t   </div>\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t  \t<!--//login-->\r\n");
      out.write("\t\t\t    <!--footer section start-->\r\n");
      out.write("\t\t\t<div class=\"footer\">\r\n");
      out.write("\t\t\t\t\t<div class=\"error-btn\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a class=\"read fourth\" href=\"index.html\">Return to Home</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t   <p>&copy 2016 Augment . All Rights Reserved | Design by <a href=\"https://w3layouts.com/\" target=\"_blank\">W3layouts.</a></p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t<!--footer section end-->\r\n");
      out.write("\t\t<!--/404-->\r\n");
      out.write("\t\t<!--js -->\r\n");
      out.write("\t\t<script src=\"js/jquery.nicescroll.js\"></script>\r\n");
      out.write("\t\t<script src=\"js/scripts.js\"></script>\r\n");
      out.write("\t\t<!-- Bootstrap Core JavaScript -->\r\n");
      out.write("\t   <script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
