/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.36
 * Generated at: 2020-03-28 15:58:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class dashboard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE HTML>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>Augment an Admin Panel Category Flat Bootstrap Responsive Web Template | Home :: w3layouts</title>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<meta name=\"keywords\" content=\"Augment Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template, \r\n");
      out.write("Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design\" />\r\n");
      out.write("<script type=\"application/x-javascript\"> addEventListener(\"load\", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>\r\n");
      out.write(" <!-- Bootstrap Core CSS -->\r\n");
      out.write("<link href=\"css/bootstrap.min.css\" rel='stylesheet' type='text/css' />\r\n");
      out.write("<!-- Custom CSS -->\r\n");
      out.write("<link href=\"css/style.css\" rel='stylesheet' type='text/css' />\r\n");
      out.write("<!-- Graph CSS -->\r\n");
      out.write("<link href=\"css/font-awesome.css\" rel=\"stylesheet\"> \r\n");
      out.write("<!-- jQuery -->\r\n");
      out.write("<link href='//fonts.googleapis.com/css?family=Roboto:700,500,300,100italic,100,400' rel='stylesheet' type='text/css'>\r\n");
      out.write("<!-- lined-icons -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/icon-font.min.css\" type='text/css' />\r\n");
      out.write("<!-- //lined-icons -->\r\n");
      out.write("<script src=\"js/jquery-1.10.2.min.js\"></script>\r\n");
      out.write("<script src=\"js/amcharts.js\"></script>\t\r\n");
      out.write("<script src=\"js/serial.js\"></script>\t\r\n");
      out.write("<script src=\"js/light.js\"></script>\t\r\n");
      out.write("<script src=\"js/radar.js\"></script>\t\r\n");
      out.write("<link href=\"css/barChart.css\" rel='stylesheet' type='text/css' />\r\n");
      out.write("<link href=\"css/fabochart.css\" rel='stylesheet' type='text/css' />\r\n");
      out.write("<!--clock init-->\r\n");
      out.write("<script src=\"js/css3clock.js\"></script>\r\n");
      out.write("<!--Easy Pie Chart-->\r\n");
      out.write("<!--skycons-icons-->\r\n");
      out.write("<script src=\"js/skycons.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script src=\"js/jquery.easydropdown.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!--//skycons-icons-->\r\n");
      out.write("</head> \r\n");
      out.write("<body>\r\n");
      out.write("   <div class=\"page-container\">\r\n");
      out.write("   <!--/content-inner-->\r\n");
      out.write("\t<div class=\"left-content\">\r\n");
      out.write("\t   <div class=\"inner-content\">\r\n");
      out.write("\t\t<!-- header-starts -->\r\n");
      out.write("\t\t\t<div class=\"header-section\">\r\n");
      out.write("\t\t\t\t\t\t<!--menu-right-->\r\n");
      out.write("\t\t\t\t\t\t<div class=\"top_menu\">\r\n");
      out.write("\t\t\t\t\t\t        <div class=\"main-search\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<form>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t   <input type=\"text\" value=\"Search\" onFocus=\"this.value = '';\" onBlur=\"if (this.value == '') {this.value = 'Search';}\" class=\"text\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"submit\" value=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"close\"><img src=\"images/cross.png\" /></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"srch\"><button></button></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t $('.main-search').hide();\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t$('button').click(function (){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t$('.main-search').show();\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t$('.main-search text').focus();\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t$('.close').click(function(){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t$('.main-search').hide();\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</script>\r\n");
      out.write("\t\t\t\t\t\t\t<!--/profile_details-->\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"profile_details_left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul class=\"nofitications-dropdown\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li class=\"dropdown note dra-down\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t   <div id=\"dd\" class=\"wrapper-dropdown-3\" tabindex=\"1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<span>Italy</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<ul class=\"dropdown\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<li><a class=\"deutsch\">France</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<li><a class=\"english\"> Italy</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<li><a class=\"espana\">Brazil</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<li><a class=\"russian\">Usa</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tfunction DropDown(el) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tthis.dd = el;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tthis.placeholder = this.dd.children('span');\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tthis.opts = this.dd.find('ul.dropdown > li');\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tthis.val = '';\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tthis.index = -1;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tthis.initEvents();\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tDropDown.prototype = {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tinitEvents : function() {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tvar obj = this;\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tobj.dd.on('click', function(event){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t$(this).toggleClass('active');\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tobj.opts.on('click',function(){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tvar opt = $(this);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tobj.val = opt.text();\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tobj.index = opt.index();\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tobj.placeholder.text(obj.val);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tgetValue : function() {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\treturn this.val;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tgetIndex : function() {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\treturn this.index;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t$(function() {\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tvar dd = new DropDown( $('#dd') );\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t$(document).click(function() {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t// all dropdowns\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t$('.wrapper-dropdown-3').removeClass('active');\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</script>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t    </li>\r\n");
      out.write("\t\t\t\t\t\t\t\t       <li class=\"dropdown note\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\" aria-expanded=\"false\"><i class=\"fa fa-envelope-o\"></i> <span class=\"badge\">3</span></a>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<ul class=\"dropdown-menu two first\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"notification_header\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<h3>You have 3 new messages  </h3> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t   <div class=\"user_img\"><img src=\"images/1.jpg\" alt=\"\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t   <div class=\"notification_desc\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<p>Lorem ipsum dolor sit amet</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<p><span>1 hour ago</span></p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t   <div class=\"clearfix\"></div>\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t </a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t <li class=\"odd\"><a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"user_img\"><img src=\"images/in.jpg\" alt=\"\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t   <div class=\"notification_desc\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<p>Lorem ipsum dolor sit amet </p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<p><span>1 hour ago</span></p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t  <div class=\"clearfix\"></div>\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t </a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t   <div class=\"user_img\"><img src=\"images/in1.jpg\" alt=\"\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t   <div class=\"notification_desc\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<p>Lorem ipsum dolor sit amet </p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<p><span>1 hour ago</span></p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t   <div class=\"clearfix\"></div>\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"notification_bottom\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"#\">See all messages</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"dropdown note\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\" aria-expanded=\"false\"><i class=\"fa fa-bell-o\"></i> <span class=\"badge\">5</span></a>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul class=\"dropdown-menu two\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"notification_header\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<h3>You have 5 new notification</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"user_img\"><img src=\"images/in.jpg\" alt=\"\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t   <div class=\"notification_desc\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<p>Lorem ipsum dolor sit amet</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<p><span>1 hour ago</span></p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t  <div class=\"clearfix\"></div>\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t </a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t <li class=\"odd\"><a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"user_img\"><img src=\"images/in5.jpg\" alt=\"\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t   <div class=\"notification_desc\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<p>Lorem ipsum dolor sit amet </p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<p><span>1 hour ago</span></p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t   <div class=\"clearfix\"></div>\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t </a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t <li><a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"user_img\"><img src=\"images/in8.jpg\" alt=\"\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t   <div class=\"notification_desc\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<p>Lorem ipsum dolor sit amet </p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<p><span>1 hour ago</span></p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t   <div class=\"clearfix\"></div>\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t </a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t <li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"notification_bottom\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"#\">See all notification</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\t\r\n");
      out.write("\t\t\t\t\t\t<li class=\"dropdown note\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\" aria-expanded=\"false\"><i class=\"fa fa-tasks\"></i> <span class=\"badge blue1\">9</span></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<ul class=\"dropdown-menu two\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"notification_header\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<h3>You have 9 pending task</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"task-info\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"task-desc\">Database update</span><span class=\"percentage\">40%</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"clearfix\"></div>\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t   </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"progress progress-striped active\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t <div class=\"bar yellow\" style=\"width:40%;\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"index.jsp\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"task-info\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"task-desc\">Dashboard done</span><span class=\"percentage\">90%</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t   <div class=\"clearfix\"></div>\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t   \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"progress progress-striped active\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t <div class=\"bar green\" style=\"width:90%;\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"task-info\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"task-desc\">Mobile App</span><span class=\"percentage\">33%</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"clearfix\"></div>\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t   <div class=\"progress progress-striped active\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t <div class=\"bar red\" style=\"width: 33%;\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"task-info\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"task-desc\">Issues fixed</span><span class=\"percentage\">80%</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t   <div class=\"clearfix\"></div>\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"progress progress-striped active\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t <div class=\"bar  blue\" style=\"width: 80%;\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"notification_bottom\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"#\">See all pending task</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\t\t   \t\t\t\t\t\t\t   \t\t\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"clearfix\"></div>\t\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"clearfix\"></div>\t\r\n");
      out.write("\t\t\t\t\t\t\t<!--//profile_details-->\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<!--//menu-right-->\r\n");
      out.write("\t\t\t\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<!-- //header-ends -->\r\n");
      out.write("\t\t\t\t\t<div class=\"outter-wp\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"colm-sm-12\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<!--footer section start-->\r\n");
      out.write("\t\t\t\t\t<footer>\r\n");
      out.write("\t\t\t\t\t\t<p>Create by <a href=\"https://github.com/Feliphegomez\" target=\"_blank\">FelipheGomez.</a></p>\r\n");
      out.write("\t\t\t\t\t</footer>\r\n");
      out.write("\t\t\t\t\t<!--footer section end-->\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!--//content-inner-->\r\n");
      out.write("\t\t\t<!--/sidebar-menu-->\r\n");
      out.write("\t\t\t<div class=\"sidebar-menu\">\r\n");
      out.write("\t\t\t\t<header class=\"logo\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" class=\"sidebar-icon\"> <span class=\"fa fa-bars\"></span> </a> <a href=\"index.jsp\"> <span id=\"logo\"> <h1>Augment</h1></span> \r\n");
      out.write("\t\t\t\t\t\t<!--<img id=\"logo\" src=\"\" alt=\"Logo\"/>--> \r\n");
      out.write("\t\t\t  \t\t</a> \r\n");
      out.write("\t\t\t\t</header>\r\n");
      out.write("\t\t\t\t<div style=\"border-top:1px solid rgba(69, 74, 84, 0.7)\"></div>\r\n");
      out.write("\t\t\t\t\t<!--/down-->\r\n");
      out.write("\t\t\t\t\t<div class=\"down\">\t\r\n");
      out.write("\t\t\t\t\t  \t<!-- <a href=\"index.jsp\"><img src=\"images/admin.jpg\"></a>-->\r\n");
      out.write("\t\t\t\t\t  \t<a href=\"index.jsp\"><span class=\" name-caret\">");
      out.print( (String)session.getAttribute("firstname") );
      out.write(' ');
      out.print( (String)session.getAttribute("lastname") );
      out.write("</span></a>\r\n");
      out.write("\t\t\t\t\t\t <p>\r\n");
      out.write("\t\t\t\t\t\t\t ");
 Integer userid = (Integer)session.getAttribute("userid"); 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t ");
      out.print( userid );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t ");
      out.print( (String)session.getAttribute("username") );
      out.write("\r\n");
      out.write("\t\t\t\t\t \t</p>\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<!-- <li><a class=\"tooltips\" href=\"index.jsp\"><span>Profile</span><i class=\"lnr lnr-user\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a class=\"tooltips\" href=\"index.jsp\"><span>Settings</span><i class=\"lnr lnr-cog\"></i></a></li> -->\r\n");
      out.write("\t\t\t\t\t\t\t<li><a class=\"tooltips\" href=\"Logout\"><span>Salir </span><i class=\"lnr lnr-power-switch\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t    <!--//down-->\r\n");
      out.write("                \t<div class=\"menu\">\r\n");
      out.write("\t\t\t\t\t\t<ul id=\"menu\" >\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"index.jsp\"><i class=\"fa fa-tachometer\"></i> <span>Dashboard</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li id=\"menu-academico\" ><a href=\"#\"><i class=\"fa fa-table\"></i> <span> Tabs &amp; Panels</span> <span class=\"fa fa-angle-right\" style=\"float: right\"></span></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul id=\"menu-academico-sub\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li id=\"menu-academico-avaliacoes\" ><a href=\"tabs.html\"> Tabs &amp; Panels</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li id=\"menu-academico-boletim\" ><a href=\"widget.html\">Widgets</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li id=\"menu-academico-avaliacoes\" ><a href=\"calender.html\">Calendar</a></li>\t\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li id=\"menu-academico\" ><a href=\"#\"><i class=\"fa fa-file-text-o\"></i> <span>Ui Elements</span> <span class=\"fa fa-angle-right\" style=\"float: right\"></span></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul id=\"menu-academico-sub\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li id=\"menu-academico-avaliacoes\" ><a href=\"forms.html\">Forms</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li id=\"menu-academico-boletim\" ><a href=\"validation.html\">Validation Forms</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li id=\"menu-academico-boletim\" ><a href=\"table.html\">Tables</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li id=\"menu-academico-boletim\" ><a href=\"buttons.html\">Buttons</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"typography.html\"><i class=\"lnr lnr-pencil\"></i> <span>Typography</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li id=\"menu-academico\" ><a href=\"#\"><i class=\"lnr lnr-book\"></i> <span>Pages</span> <span class=\"fa fa-angle-right\" style=\"float: right\"></span></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul id=\"menu-academico-sub\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t    <li id=\"menu-academico-avaliacoes\" ><a href=\"login.html\">Login</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t    <li id=\"menu-academico-boletim\" ><a href=\"register.html\">Register</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li id=\"menu-academico-boletim\" ><a href=\"404.html\">404</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li id=\"menu-academico-boletim\" ><a href=\"sign.html\">Sign up</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li id=\"menu-academico-boletim\" ><a href=\"profile.html\">Profile</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\"><i class=\"lnr lnr-envelope\"></i> <span>Mail Box</span><span class=\"fa fa-angle-right\" style=\"float: right\"></span></a>\r\n");
      out.write("\t\t\t\t\t\t\t   \t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"inbox.html\"><i class=\"fa fa-inbox\"></i> Inbox</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"compose.html\"><i class=\"fa fa-pencil-square-o\"></i> Compose Mail</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"editor.html\"><span class=\"lnr lnr-highlight\"></span> Editors Page</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t  \t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t        <li id=\"menu-academico\" ><a href=\"#\"><i class=\"lnr lnr-layers\"></i> <span>Components</span> <span class=\"fa fa-angle-right\" style=\"float: right\"></span></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t <ul id=\"menu-academico-sub\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li id=\"menu-academico-avaliacoes\" ><a href=\"grids.html\">Grids</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li id=\"menu-academico-boletim\" ><a href=\"media.html\">Media Objects</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"chart.html\"><i class=\"lnr lnr-chart-bars\"></i> <span>Charts</span> <span class=\"fa fa-angle-right\" style=\"float: right\"></span></a>\r\n");
      out.write("\t\t\t\t\t\t\t  \t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"map.html\"><i class=\"lnr lnr-map\"></i> Maps</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"graph.html\"><i class=\"lnr lnr-apartment\"></i> Graph Visualization</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li id=\"menu-comunicacao\" ><a href=\"#\"><i class=\"fa fa-smile-o\"></i> <span>More</span><span class=\"fa fa-angle-double-right\" style=\"float: right\"></span></a>\r\n");
      out.write("\t\t\t\t\t\t\t  \t<ul id=\"menu-comunicacao-sub\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li id=\"menu-mensagens\" style=\"width:120px\" ><a href=\"project.html\">Projects <i class=\"fa fa-angle-right\" style=\"float: right; margin-right: -8px; margin-top: 2px;\"></i></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<ul id=\"menu-mensagens-sub\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li id=\"menu-mensagens-enviadas\" style=\"width:130px\" ><a href=\"ribbon.html\">Ribbons</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li id=\"menu-mensagens-recebidas\"  style=\"width:130px\"><a href=\"blank.html\">Blank</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li id=\"menu-arquivos\" ><a href=\"500.html\">500</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"clearfix\"></div>\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<script>\r\n");
      out.write("\t\tvar toggle = true;\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t$(\".sidebar-icon\").click(function() {                \r\n");
      out.write("\t\t  if (toggle)\r\n");
      out.write("\t\t  {\r\n");
      out.write("\t\t\t$(\".page-container\").addClass(\"sidebar-collapsed\").removeClass(\"sidebar-collapsed-back\");\r\n");
      out.write("\t\t\t$(\"#menu span\").css({\"position\":\"absolute\"});\r\n");
      out.write("\t\t  }\r\n");
      out.write("\t\t  else\r\n");
      out.write("\t\t  {\r\n");
      out.write("\t\t\t$(\".page-container\").removeClass(\"sidebar-collapsed\").addClass(\"sidebar-collapsed-back\");\r\n");
      out.write("\t\t\tsetTimeout(function() {\r\n");
      out.write("\t\t\t  $(\"#menu span\").css({\"position\":\"relative\"});\r\n");
      out.write("\t\t\t}, 400);\r\n");
      out.write("\t\t  }\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\ttoggle = !toggle;\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t\t<!--js -->\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"css/vroom.css\">\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"js/vroom.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"js/TweenLite.min.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"js/CSSPlugin.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"js/jquery.nicescroll.js\"></script>\r\n");
      out.write("\t\t<script src=\"js/scripts.js\"></script>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- Bootstrap Core JavaScript -->\r\n");
      out.write("\t   \t<script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
